# MYSQL
db.mysql.url=jdbc:mysql://localhost:3306/ERDB
db.mysql.user=root
db.mysql.pass=GM*UPr3s4sP@#

# POSTGRESQL
db.postgres.url=jdbc:postgresql://localhost:5432/ERDB
db.postgres.user=root
db.postgres.pass=Blanes2007!